"use client";

import React, { useState } from 'react';
import { PanelLayout } from '@/layouts/PanelLayout';
import { Card } from '@/components/Card';
import { Button } from '@/components/Button';
import {
    FileText,
    Plus,
    Search,
    Download,
    Share2,
    Clock,
    MoreHorizontal,
    Sparkles,
    FileCode,
    FileSignature,
    ChevronRight,
    Loader2,
    History
} from 'lucide-react';
import { cn } from '@/app/lib/utils';

export default function DocumentsPage() {
    const [activeDoc, setActiveDoc] = useState<any>({
        title: 'Project Requirements.md',
        content: '# Project Requirements\n\nGenerated by AI. Select a template to begin.',
        lastModified: 'Today, 10:45 AM',
        type: 'markdown'
    });

    const [isGenerating, setIsGenerating] = useState(false);

    const handleGenerateDoc = async (type: string, customPrompt?: string) => {
        setIsGenerating(true);
        try {
            const description = customPrompt || `Generate a comprehensive ${type} for a new project.`;
            const response = await fetch('http://localhost:5000/api/ai/generate-doc', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ description })
            });
            if (response.ok) {
                const data = await response.json();
                setActiveDoc({
                    title: `${type.split(' ')[0]}.md`,
                    content: data.content,
                    lastModified: 'Just now',
                    type: 'markdown'
                });
            }
        } catch (error) {
            console.error("Failed to generate doc", error);
            alert("Failed to generate document");
        } finally {
            setIsGenerating(false);
        }
    };

    const handleDownloadWord = async () => {
        try {
            const response = await fetch('http://localhost:5000/api/ai/export-word', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    title: activeDoc.title,
                    content: activeDoc.content
                })
            });
            if (response.ok) {
                const blob = await response.blob();
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${activeDoc.title.replace('.md', '')}.docx`;
                document.body.appendChild(a);
                a.click();
                a.remove();
            }
        } catch (error) {
            console.error("Failed to download", error);
            alert("Failed to export to Word");
        }
    };

    return (
        <PanelLayout role="employee">
            <div className="flex h-[calc(100vh-120px)] border border-notion-border rounded-lg bg-white overflow-hidden shadow-sm">
                {/* Sidebar */}
                <div className="w-72 bg-notion-sidebar border-r border-notion-border flex flex-col">
                    <div className="p-4 border-b border-notion-border">
                        <div className="flex items-center justify-between mb-4">
                            <h2 className="text-xs font-black uppercase text-gray-400 tracking-widest">Documents</h2>
                            <Button variant="ghost" size="sm" className="p-1 h-auto text-gray-400 hover:text-jira-orange">
                                <Plus size={16} />
                            </Button>
                        </div>
                        <div className="relative">
                            <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 text-gray-400" size={14} />
                            <input
                                type="text"
                                placeholder="Search files..."
                                className="w-full pl-8 pr-3 py-1.5 text-xs bg-white border border-notion-border rounded-md focus:outline-none"
                            />
                        </div>
                    </div>
                    <div className="flex-1 overflow-y-auto p-2 space-y-1">
                        <div className="px-3 py-2 text-[11px] font-bold text-gray-400 uppercase tracking-wider">Templates</div>
                        <button onClick={() => handleGenerateDoc('Software Requirements Document (SRD)')} className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-notion-text hover:bg-white/50 rounded-md group transition-colors">
                            <FileCode size={14} className="text-blue-500" /> SRD Template
                        </button>
                        <button onClick={() => handleGenerateDoc('System Design Document (SSD)')} className="w-full flex items-center gap-2.5 px-3 py-2 text-xs text-notion-text hover:bg-white/50 rounded-md group transition-colors">
                            <FileSignature size={14} className="text-purple-500" /> SSD Template
                        </button>
                    </div>
                </div>

                {/* Main Content Area */}
                <div className="flex-1 flex flex-col bg-white">
                    {/* Toolbar */}
                    <div className="h-14 border-b border-notion-border flex items-center justify-between px-6">
                        <div className="flex items-center gap-3">
                            <div className="px-2 py-1 bg-orange-50 text-jira-orange rounded text-[10px] font-black uppercase tracking-widest border border-orange-100">
                                {activeDoc.type}
                            </div>
                            <h1 className="text-sm font-bold text-notion-text">{activeDoc.title}</h1>
                        </div>
                        <div className="flex items-center gap-2">
                            <Button variant="ghost" size="sm" className="text-gray-500 gap-2">
                                <Share2 size={14} /> Share
                            </Button>
                            <Button
                                variant="outline"
                                size="sm"
                                className="text-jira-orange border-orange-100 bg-orange-50/20 gap-2 hover:bg-orange-50"
                                onClick={handleDownloadWord}
                                disabled={isGenerating}
                            >
                                <Download size={14} /> Export to Word
                            </Button>
                        </div>
                    </div>

                    {/* Editor / Viewer */}
                    <div className="flex-1 overflow-y-auto p-12 custom-scrollbar">
                        <div className="max-w-3xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-500">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center gap-2 text-gray-400 text-xs">
                                    <Clock size={14} /> Last modified {activeDoc.lastModified}
                                </div>
                                <Button variant="ghost" className="text-gray-400 text-xs gap-2">
                                    <History size={14} /> View history
                                </Button>
                            </div>

                            <div className="prose prose-sm max-w-none whitespace-pre-wrap font-mono text-notion-text bg-gray-50/50 p-8 rounded-xl border border-dashed border-gray-200 min-h-[400px]">
                                {isGenerating ? (
                                    <div className="flex flex-col items-center justify-center py-20 gap-4">
                                        <Loader2 className="text-jira-orange animate-spin" size={32} />
                                        <p className="text-sm font-bold text-gray-400 animate-pulse">Gemini AI is generating your document...</p>
                                    </div>
                                ) : (
                                    activeDoc.content
                                )}
                            </div>

                            {/* Assistant Panel */}
                            <Card className="p-6 bg-gradient-to-br from-blue-50/50 to-purple-50/50 border-blue-100/50 shadow-none">
                                <div className="flex items-start gap-4">
                                    <div className="p-2 bg-white rounded-lg shadow-sm">
                                        <Sparkles className="text-jira-orange" size={20} />
                                    </div>
                                    <div className="space-y-3 flex-1">
                                        <div>
                                            <h4 className="text-sm font-bold text-notion-text">AI Assistant</h4>
                                            <p className="text-xs text-gray-500">Generate high-quality documentation in seconds.</p>
                                        </div>
                                        <div className="flex flex-wrap gap-2">
                                            <Button
                                                variant="outline"
                                                size="sm"
                                                className="bg-white text-[10px] h-7 px-3 font-bold"
                                                onClick={() => handleGenerateDoc('Software Requirements (SRD)')}
                                            >
                                                Generate SRD
                                            </Button>
                                            <Button
                                                variant="outline"
                                                size="sm"
                                                className="bg-white text-[10px] h-7 px-3 font-bold"
                                                onClick={() => handleGenerateDoc('System Design (SSD)')}
                                            >
                                                Generate SSD
                                            </Button>
                                            <Button variant="outline" size="sm" className="bg-white text-[10px] h-7 px-3 font-bold">Write Test Plan</Button>
                                        </div>
                                    </div>
                                </div>
                            </Card>
                        </div>
                    </div>
                </div>
            </div>
        </PanelLayout>
    );
}
